### PR TITLE
Inches: anything not between -9 and 9 parses incorrectly

### LINKED ISSUE #238: Inches: anything not between -9 and 9 parses incorrectly
When using inches, if no spaces are used between the number and unit and a number is more than 1-digit (positive or negative) Unit.new throws an error stating ```ArgumentError: 'n' Unit not recognized```. It seems that it is removing the "i" in "in," "inch," and "inches." Using the double-quote symbol for inches works fine.

Working examples:
```ruby
RubyUnits::Unit.new('9in')          # => 9 in
RubyUnits::Unit.new('-9in')         # => -9 in
RubyUnits::Unit.new('-10"')         # => -10 in
RubyUnits::Unit.new('100"')         # => 100 in
RubyUnits::Unit.new('100 in')       # => 100 in
RubyUnits::Unit.new('100 inches')   # => 100 in
```

Examples that throw an error:
```ruby
RubyUnits::Unit.new('10in')         # => ArgumentError: 'n' Unit not recognized
RubyUnits::Unit.new('-10inch')      # => ArgumentError: 'nch' Unit not recognized
RubyUnits::Unit.new('100inches')    # => ArgumentError: 'nches' Unit not recognized
```

It is almost like it seems to be recognized as a complex number, but looking at the regex, I don't think that's the case since it has ```\b``` at the end.

```ruby
COMPLEX_NUMBER     = /#{SCI_NUMBER}?#{SCI_NUMBER}i\b/
```

Here is the stack trace:
```
ArgumentError: 'n' Unit not recognized
    /usr/local/bundle/gems/ruby-units-2.3.2/lib/ruby_units/unit.rb:1621:in `parse'
    /usr/local/bundle/gems/ruby-units-2.3.2/lib/ruby_units/unit.rb:525:in `initialize'
    /usr/local/bundle/gems/ruby-units-2.3.2/lib/ruby_units/string.rb:6:in `new'
    /usr/local/bundle/gems/ruby-units-2.3.2/lib/ruby_units/string.rb:6:in `to_unit'
    /usr/local/bundle/gems/ruby-units-2.3.2/lib/ruby_units/unit.rb:537:in `initialize'
```

### PR DESCRIPTION
**Pull request by olbrich**
There was inconsistent usage of some regular expressions that ended up matching `99in` with a complex number. Refactoring and cleaning up the related code and regexes makes it work now.

Fixes #238

### CODE REVIEW

File: lib/ruby_units/configuration.rb [hunk 1]
```diff
@@ -24,17 +24,18 @@ def self.configure
 
   # holds actual configuration values for RubyUnits
   class Configuration
-    # used to separate the scalar from the unit when generating output.
-    # set to nil to prevent adding a space to the string representation of a unit
-    # separators other than ' ' and '' may work, but you may encounter problems
+    # Used to separate the scalar from the unit when generating output. A value
```
Comment (olbrich) [inline lib/ruby_units/configuration.rb:27]: Initially I thought the problem might be related to the optional separator feature. That was wrong, but I noticed that the documentation was also wrong, so I fixed it.

File: lib/ruby_units/definition.rb [hunk 2]
```diff
@@ -57,7 +61,7 @@ def name=(name_value)
     # alias array must contain the name of the unit and entries must be unique
     # @return [Array]
     def aliases
-      [[@aliases], @name].flatten.compact.uniq
+      [[@aliases], @name, @display_name].flatten.compact.uniq
```
Comment (olbrich) [inline lib/ruby_units/definition.rb:64]: Fixing the actual bug exposed another one related to display names

File: lib/ruby_units/unit.rb [hunk 3]
```diff
@@ -31,30 +31,41 @@ class Unit < Numeric
...
-    UNIT_STRING_REGEX  = %r{#{SCI_NUMBER}*\s*([^\/]*)\/*(.+)*}
-    TOP_REGEX          = /([^ \*]+)(?:\^|\*\*)([\d-]+)/
-    BOTTOM_REGEX       = /([^* ]+)(?:\^|\*\*)(\d+)/
-    NUMBER_UNIT_REGEX  = /#{SCI_NUMBER}?(.*)/
-    COMPLEX_REGEX      = /#{COMPLEX_NUMBER}\s?(.+)?/
-    RATIONAL_REGEX     = /#{RATIONAL_NUMBER}\s?(.+)?/
+    # ideally we would like to generate this regex from the alias for a 'feet'
+    # and 'inches', but they aren't defined at the point in the code where we
+    # need this regex.
+    FEET_INCH_UNITS_REGEX = /(?:'|ft|feet)\s*(\d+)\s*(?:"|in|inch(?:es)?)/.freeze
```
Comment (olbrich) [inline lib/ruby_units/unit.rb:37]: Mostly freezing regexes and adding documentation. This way we don't redefine a bunch of Regexes that get used a lot every time we parse a unit.

File: lib/ruby_units/unit.rb [hunk 4]
```diff
@@ -304,40 +318,23 @@ def self.base_units
...
-          # if it has whitespace, it will be of the form '6 1/2'
-          if num =~ RATIONAL_NUMBER
-            sign = Regexp.last_match(1) == '-' ? -1 : 1
-            n = Regexp.last_match(2).to_i
-            f = Rational(Regexp.last_match(3).to_i, Regexp.last_match(4).to_i)
-            sign * (n + f)
-          else
-            Rational(*num.split('/').map(&:to_i))
-          end
+        when COMPLEX_NUMBER
```
Comment (olbrich) [inline lib/ruby_units/unit.rb:329]: Use the same Regexp everywhere. Also we dropped the special handling for complex numbers because that hasn't been necessary for a very long time.

File: lib/ruby_units/unit.rb [hunk 5]
```diff
@@ -528,11 +526,12 @@ def initialize(*options)
       end
       update_base_scalar
       raise ArgumentError, 'Temperatures must not be less than absolute zero' if temperature? && base_scalar < 0
+
       unary_unit = units || ''
       if options.first.instance_of?(String)
         _opt_scalar, opt_units = self.class.parse_into_numbers_and_units(options[0])
         unless  @@cached_units.keys.include?(opt_units) ||
-                (opt_units =~ %r{\D/[\d+\.]+}) ||
```
Comment (olbrich) [inline lib/ruby_units/unit.rb:535]: Remove extraneous escape.
